spring:
  application:
    name: mybox
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  docker:
    compose:
      file: compose.yml

server:
  address: 0.0.0.0
  port: 8080

springdoc:
  enable-kotlin: false
